/*
 * H.264/HEVC/AV1 hardware encoding using nvidia nvenc
 * Copyright (c) 2025 Wang Bin <wbsecg1 at gmail.com>
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include "nvenc.h"

/*
 To support all version of nvEncodeAPI.h with minimal changes, we need to dispatch ff_nvenc_* to versioned functions.
 nvenc.c is built against the latest version(13.0).
 nvenc_111.c is built against version 11.1, which is the highest version that abi compatible with all lower versions
 To use nvEncodeAPI.h of a lower version, e.g. 11.1, we need a copy of the header, additional cflags, and include the header

 #include <nv-codec-headers11.1/include/ffnvcodec/nvEncodeAPI.h>

 before nvenc.c, thus <ffnvcodec/nvEncodeAPI.h> in nvenc.h will be ignored and only the lower version will be used.

 10.0 defines a different set of preset guids, so building against 9.1 header is required.
 preset option default value in nvenc_$codec.c is version dependent but only they are built only once, so manually setting preset
 for version < 10.0 is required.
 TODO: This dispatch file(at least version suffix) and other versioned nvenc_*.c should be generated by a script.
*/
int ff_nvenc_encode_init131(AVCodecContext *avctx);
int ff_nvenc_encode_close131(AVCodecContext *avctx);
int ff_nvenc_receive_packet131(AVCodecContext *avctx, AVPacket *pkt);
void ff_nvenc_encode_flush131(AVCodecContext *avctx);

int ff_nvenc_encode_init121(AVCodecContext *avctx);
int ff_nvenc_encode_close121(AVCodecContext *avctx);
int ff_nvenc_receive_packet121(AVCodecContext *avctx, AVPacket *pkt);
void ff_nvenc_encode_flush121(AVCodecContext *avctx);

int ff_nvenc_encode_init120(AVCodecContext *avctx);
int ff_nvenc_encode_close120(AVCodecContext *avctx);
int ff_nvenc_receive_packet120(AVCodecContext *avctx, AVPacket *pkt);
void ff_nvenc_encode_flush120(AVCodecContext *avctx);

int ff_nvenc_encode_init111(AVCodecContext *avctx);
int ff_nvenc_encode_close111(AVCodecContext *avctx);
int ff_nvenc_receive_packet111(AVCodecContext *avctx, AVPacket *pkt);
void ff_nvenc_encode_flush111(AVCodecContext *avctx);

#if !__has_include(<nv-codec-headers-12.1/include/ffnvcodec/nvEncodeAPI.h>)
av_cold int ff_nvenc_encode_init121(AVCodecContext *avctx) { return AVERROR_EXTERNAL; }
av_cold int ff_nvenc_encode_close121(AVCodecContext *avctx) { return AVERROR_EXTERNAL; }
int ff_nvenc_receive_packet121(AVCodecContext *avctx, AVPacket *pkt) { return AVERROR_EXTERNAL; }
av_cold void ff_nvenc_encode_flush121(AVCodecContext *avctx) {}
#endif

#if !__has_include(<nv-codec-headers-12.0/include/ffnvcodec/nvEncodeAPI.h>)
av_cold int ff_nvenc_encode_init120(AVCodecContext *avctx) { return AVERROR_EXTERNAL; }
av_cold int ff_nvenc_encode_close120(AVCodecContext *avctx) { return AVERROR_EXTERNAL; }
int ff_nvenc_receive_packet120(AVCodecContext *avctx, AVPacket *pkt) { return AVERROR_EXTERNAL; }
av_cold void ff_nvenc_encode_flush120(AVCodecContext *avctx) {}
#endif

#if !__has_include(<nv-codec-headers-11.1/include/ffnvcodec/nvEncodeAPI.h>)
av_cold int ff_nvenc_encode_init111(AVCodecContext *avctx) { return AVERROR_EXTERNAL; }
av_cold int ff_nvenc_encode_close111(AVCodecContext *avctx) { return AVERROR_EXTERNAL; }
int ff_nvenc_receive_packet111(AVCodecContext *avctx, AVPacket *pkt) { return AVERROR_EXTERNAL; }
av_cold void ff_nvenc_encode_flush111(AVCodecContext *avctx) {}
#endif

static const char* nvenc_driver_requirement(float api)
{
    const struct {
        float api;
        const char* win;
        const  char* linux;
    } requirements[] = {
        {13.2f, "(unknown)", "(unknown)"},
        {13.1f, "610.00", "610.00"},
        {13.0f, "570.0", "570.0"},
        {12.2f, "551.76", "550.54.14"},
        {12.1f, "531.61", "530.41.03"},
        {12.0f, "522.25", "520.56.06"},
        {11.1f, "471.41", "470.57.02"},
        {11.0f, "456.71", "455.28"},
        {10.0f, "450.51", "445.87"},
        {9.1f,  "436.15", "435.21"},
        {9.0f,  "418.81", "418.30"},
        {8.2f,  "397.93", "396.24"},
        {8.1f,  "390.77", "390.25"},
        {8.0f,  "378.66", "378.13"},
    };

    for (int i = 0; i < FF_ARRAY_ELEMS(requirements); i++) {
        if (requirements[i].api <= api) {
#if defined(_WIN32) || defined(__CYGWIN__)
            return requirements[i].win;
#else
            return requirements[i].linux;
#endif
        }
    }
    return "(unknown)";
}

static av_cold int nvenc_load_api(AVCodecContext *avctx)
{
    NvencContext *ctx            = avctx->priv_data;
    NvencDynLoadFunctions *dl_fn = &ctx->nvenc_dload_funcs;
    NVENCSTATUS err;
    uint32_t nvenc_max_ver;
    uint32_t nvenc_max_major;
    uint32_t nvenc_max_minor;
    int ret;
    ret = nvenc_load_functions(&dl_fn->nvenc_dl, avctx);
    if (ret < 0) {
        av_log(avctx, AV_LOG_ERROR, "nvenc_load_functions error\n");
        return ret;
    }

    err = dl_fn->nvenc_dl->NvEncodeAPIGetMaxSupportedVersion(&nvenc_max_ver);
    if (err != NV_ENC_SUCCESS) {
        av_log(avctx, AV_LOG_ERROR, "Failed to query nvenc max version\n");
        return AVERROR_UNKNOWN;
    }
    nvenc_max_major = nvenc_max_ver >> 4;
    nvenc_max_minor = nvenc_max_ver & 0xf;

    if (ctx->apiver_req <= 0) {
        ctx->apiver_req = nvenc_max_major + nvenc_max_minor / 10.0f;
    }
    if (ctx->apiver_req > nvenc_max_major + nvenc_max_minor / 10.0f) {
        av_log(avctx, AV_LOG_ERROR, "Requested nvenc API version %.1f is not supported, the minimum required Nvidia driver is %s\n", ctx->apiver_req, nvenc_driver_requirement(ctx->apiver_req));
        return AVERROR(ENOSYS);
    }
    return 0;
}

av_cold int ff_nvenc_encode_init(AVCodecContext *avctx)
{
    nvenc_load_api(avctx); // don't return error, a future version may be supported
    NvencContext *ctx = avctx->priv_data;
    if (ctx->apiver_req >= 12.2f)
        return ff_nvenc_encode_init131(avctx);
    if (ctx->apiver_req >= 12.1f)
        return ff_nvenc_encode_init121(avctx);
    if (ctx->apiver_req >= 12.0f)
        return ff_nvenc_encode_init120(avctx);
    return ff_nvenc_encode_init111(avctx);
}

av_cold int ff_nvenc_encode_close(AVCodecContext *avctx)
{
    NvencContext *ctx = avctx->priv_data;
    if (ctx->apiver_req >= 12.2f)
        return ff_nvenc_encode_close131(avctx);
    if (ctx->apiver_req >= 12.1f)
        return ff_nvenc_encode_close121(avctx);
    if (ctx->apiver_req >= 12.0f)
        return ff_nvenc_encode_close120(avctx);
    return ff_nvenc_encode_close111(avctx);
}

int ff_nvenc_receive_packet(AVCodecContext *avctx, AVPacket *pkt)
{
    NvencContext *ctx = avctx->priv_data;
    if (ctx->apiver_req >= 12.2f)
        return ff_nvenc_receive_packet131(avctx, pkt);
    if (ctx->apiver_req >= 12.1f)
        return ff_nvenc_receive_packet121(avctx, pkt);
    if (ctx->apiver_req >= 12.0f)
        return ff_nvenc_receive_packet120(avctx, pkt);
    return ff_nvenc_receive_packet111(avctx, pkt);
}

av_cold void ff_nvenc_encode_flush(AVCodecContext *avctx)
{
    NvencContext *ctx = avctx->priv_data;
    if (ctx->apiver_req >= 12.2f)
        return ff_nvenc_encode_flush131(avctx);
    if (ctx->apiver_req >= 12.1f)
        return ff_nvenc_encode_flush121(avctx);
    if (ctx->apiver_req >= 12.0f)
        return ff_nvenc_encode_flush120(avctx);
    return ff_nvenc_encode_flush111(avctx);
}